enabel_user:
    login_redirect_route: 'app_home'
    user_class: 'App\Entity\Enabel\User'
    user_repository: 'App\Repository\Enabel\UserRepository'

knpu_oauth2_client:
    clients:
        azure_o365:
            type: azure
            client_id: '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_CLIENT_SECRET)%'
            api_version: 'v1.0'
            url_api: 'https://graph.microsoft.com/'
            redirect_route: enabel_azure_check
